### ISSUE TITLE
Remove Go Fund Me link & replace fundraising text

### ISSUE THREAD

**Issue by lucylightly** [savebrowntrack/savebrowntrack.github.io#17]
Please change the key text:
			<p>For now, our key focus lies in advocacy and mobilization towards more just and equitable outcomes for athletes, alumni, and future students. If you would be interested in witholding your donation to Brown until this issue is resolved, please drop us an email in the form below.</p>

...Then remove this link!

**Comment by savebrowntrack** [comment]
done diddley
