### ISSUE TITLE
Add "Excellence + Analytics" section

### ISSUE THREAD

**Issue by lucylightly** [savebrowntrack/savebrowntrack.github.io#20]
Please see the "Excellence + Analytics" text and layout here: https://docs.google.com/document/d/1DrMLlHWcmg_6EyV2iwEHgm1tP4nhHTs6CvXPmQQHgcM/edit 

**LINKS TO IMAGES:**
FalseStart to Excellence img 1 (left): https://github.com/savebrowntrack/savebrowntrack.github.io/blob/master/analyses_and_visualizations/figures/accolades/numberAllAmericans_BrownTeams.png
FalseStart to Excellence img 2 (right): https://drive.google.com/file/d/1KKC2jXeZ_o0ITrweKW7weDC1LvTvHF3J/view?usp=sharing

FalseStart to Diversity img 1 (left):  https://github.com/savebrowntrack/savebrowntrack.github.io/blob/master/analyses_and_visualizations/figures/diversity/racial_diversity_percent.png
FalseStart to Diversity img 2 (right):
https://github.com/savebrowntrack/savebrowntrack.github.io/blob/master/analyses_and_visualizations/figures/diversity/racial_diversity_absolute.png

FalseStart to Values img 1 (left): 
https://github.com/savebrowntrack/savebrowntrack.github.io/blob/master/analyses_and_visualizations/figures/financial/costs_per_athlete.webpage.png
FalseStart to Values img 2 (right):
https://github.com/savebrowntrack/savebrowntrack.github.io/blob/master/analyses_and_visualizations/figures/financial/total_costs_per_team.webpage.png

**Comment by savebrowntrack** [comment]
We are gonna upload the images and style them, but we'll need more from the content team here. Not sure if we should publish it with the soft launch if that's tomorrow

**Comment by savebrowntrack** [comment]
Done but it's bad
