### ISSUE TITLE
Update "Get in touch" section on .index 

### ISSUE THREAD

**Issue by lucylightly** [savebrowntrack/savebrowntrack.github.io#22]
We need to be clearer with our ask! Rather than "if you want to submit anything," let's do this right above the form: 

		<h3>If you would like to offer skills, connections, ideas, or words of support</h3>
		<h2>Please get in touch</h2>
		<h3>Your emails will be treated carefully, and with great respect.</h3>

**Comment by savebrowntrack** [comment]
done!
