### ISSUE TITLE
Update Landing Page Photo

### ISSUE THREAD

**Issue by lucylightly** [savebrowntrack/savebrowntrack.github.io#23]
The baton passing graphic - though cool - shows two white hands and a dated hashtag. Please replace it with this graphic: https://drive.google.com/drive/folders/1DxKfI-UAo5QIlun5Vm5oy8EyN3Rpt46i 

And bold red text saying:
REINSTATE BROWN MEN'S TRACK AND FIELD / CROSS COUNTRY

**Comment by lucylightly** [comment]
(by "landing page" i mean "index")

**Comment by savebrowntrack** [comment]
I just updated it to be a video, which I think looks really good. Should I change it to the image instead?
