### ISSUE TITLE
Preview text for spotlights on the home page needs to be updated!

### ISSUE THREAD

**Issue by lucylightly** [savebrowntrack/savebrowntrack.github.io#30]
Hi guys! On the home/index page, we have these spotlights and preview text that show up when you hover over the image. The existing order of the athletes is perfect. But could you please plug the values below in as the preview texts, rather than the long sentence excerpts that currently exist there?

Bretram: "Access and Family"
Brian: "1984 Doublespeak"
Brynn: "Perpetuating Structures of Inequity"
Carly: "Breadth of Excellence"
Duriel: "True Diversity and Inclusion"
Trinity Gray: "An Example of Institutionalized Racism"

**Comment by lucylightly** [comment]
SORRY UPDATE From Brian the spotlight-ee - just got it

He woudl like his profile LAST in the order of spotlights

**Comment by savebrowntrack** [comment]
fixed
