### ISSUE TITLE
High Priority -- "Analytics and Excellence"

### ISSUE THREAD

**Issue by lucylightly** [savebrowntrack/savebrowntrack.github.io#34]
Add Calvin's edits for text, plus the new graphic and section at the bottom. 

Academic All American graphic is missing. That can be found here: https://github.com/savebrowntrack/savebrowntrack.github.io/blob/master/analyses_and_visualizations/figures/accolades/academicIvyAwards_BrownTeams.png

**Comment by savebrowntrack** [comment]
Pretty sure calvin did this
